config/routes.rb
GameOn::Application.routes.draw do

  match 'feedbacks' => 'feedbacks#create', :as => :feedback, via: :post
  match 'feedbacks/new' => 'feedbacks#new', :as => :new_feedback, via: :get
  
  resources :rec_event_follows do
    collection do
      get 'mygames'
    end
  end

  resources :event_invites

  resources :events do
    collection do
      get 'rsvp_yes'
      get 'rsvp_no'
      get 'rsvp_maybe'
      post 'comment'
    end
    resources :event_comments
  end

  resources :game_types
  resources :recurring_events do
    collection do
      get 'nearby'
      get 'follow'
      get 'unfollow'
    end
  end

  resources :locations do
    collection do
      get 'nearby'
    end
  end

  resources :user_profiles do
    collection do
      get 'editself'
    end
  end
  
  resources :home 
  
  authenticated :user do
    root :to => 'home#index', as: 'authorized'
  end
  root :to => "users#index"
  
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  

  

end

app/models/rec_event_follow.rb
class RecEventFollow < ActiveRecord::Base
  attr_accessible  :recurring_event_id, :user_id, :send_email, :send_sms
  belongs_to :recurring_event
  belongs_to :user
end

app/controllers/rec_event_follows_controller.rb
class RecEventFollowsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_rec_event_follow, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /rec_event_follows
  # GET /rec_event_follows.json
  def index
    @rec_event_follows = RecEventFollow.all
    authorize! :index, RecEventFollow.new, :message => 'Not authorized as an administrator.'
  end

  def mygames
    #@rec_event_follows = RecEventFollow.all
    @rec_event_follows = RecEventFollow.includes(:recurring_event).where("user_id = ?", current_user.id).references(:recurring_event).order('recurring_events.day')
    authorize! :mygames, RecEventFollow.new, :message => 'Not authorized as an administrator.'
  end
  
  # GET /rec_event_follows/1
  # GET /rec_event_follows/1.json
  def show
    authorize! :show, @rec_event_follow, :message => 'Not authorized as an administrator.'
  end

  # GET /rec_event_follows/new
  def new
    @rec_event_follow = RecEventFollow.new
    authorize! :create, @rec_event_follow, :message => 'Not authorized as an administrator.'
  end

  # GET /rec_event_follows/1/edit
  def edit
    authorize! :edit, @rec_event_follow, :message => 'Not authorized as an administrator.'
  end

  # POST /rec_event_follows
  # POST /rec_event_follows.json
  def create
    @rec_event_follow = RecEventFollow.new(rec_event_follow_params)
    authorize! :create, @rec_event_follow, :message => 'Not authorized as an administrator.'
    respond_to do |format|
      if @rec_event_follow.save
        format.html { redirect_to @rec_event_follow, notice: 'Rec event follow was successfully created.' }
        format.json { render action: 'show', status: :created, location: @rec_event_follow }
      else
        format.html { render action: 'new' }
        format.json { render json: @rec_event_follow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rec_event_follows/1
  # PATCH/PUT /rec_event_follows/1.json
  def update
    respond_to do |format|
      authorize! :update, @rec_event_follow, :message => 'Not authorized as an administrator.'
      if @rec_event_follow.update(rec_event_follow_params)
        format.html { redirect_to @rec_event_follow, notice: 'Rec event follow was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @rec_event_follow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rec_event_follows/1
  # DELETE /rec_event_follows/1.json
  def destroy
    authorize! :destroy, @rec_event_follow, :message => 'Not authorized as an administrator.'
    @rec_event_follow.destroy
    respond_to do |format|
      format.html { redirect_to rec_event_follows_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rec_event_follow
      @rec_event_follow = RecEventFollow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rec_event_follow_params
      params.require(:rec_event_follow).permit(:recurring_event_id, :user_id, :send_email, :send_sms)
    end
  
end

app/helpers/rec_event_follows_helper.rb
module RecEventFollowsHelper
end

app/views/rec_event_follows/_form.html.erb
<%= simple_form_for(@rec_event_follow) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :recurring_event_id %>
    <%= f.input :user_id %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/rec_event_follows/_mygames.html.erb
<% if @rec_event_follows %>
  <% @rec_event_follows.each do |r | %>
    <div class="mygames">
      <%= link_to r.recurring_event do %>
        <div style='position:relative'>
          <span class='linkedspan'></span>       
          <strong><%= link_to Date::DAYNAMES[ r.recurring_event.day ],  r.recurring_event.location.name  %> </strong>
          <div>
              <%= r.recurring_event.name %> - <%= r.recurring_event.game_type.name %>
          </div>
          <div>
            <%=  get_timestring( r.recurring_event.start_time, r.recurring_event.end_time ) %>
          </div>
          <div>
            <%= r.recurring_event.location.name %>
          </div>
          <span class="stars"><%= r.recurring_event.level %></span>   
      </div>
      <br>
      <% end %>
    </div>
  <% end %>
  <% else %>
  <p> You do not have any recurring games </p>
<p> 
<% end %>

app/views/rec_event_follows/edit.html.erb
<h1>Editing rec_event_follow</h1>

<%= render 'form' %>

<%= link_to 'Show', @rec_event_follow %> |
<%= link_to 'Back', rec_event_follows_path %>

app/views/rec_event_follows/index.html.erb
<h1>Listing rec_event_follows</h1>

<table>
  <thead>
    <tr>
      <th>Recurring event</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @rec_event_follows.each do |rec_event_follow| %>
      <tr>
        <td><%= rec_event_follow.recurring_event_id %></td>
        <td><%= rec_event_follow.user_id %></td>
        <td><%= link_to 'Show', rec_event_follow %></td>
        <td><%= link_to 'Edit', edit_rec_event_follow_path(rec_event_follow) %></td>
        <td><%= link_to 'Destroy', rec_event_follow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rec event follow', new_rec_event_follow_path %>

app/views/rec_event_follows/mygames.html.erb
<h3 style="margin-top: 0px">My Weekly Games</h3>
<div id='mygames' >
  <%= render 'mygames' %>  
</div>

app/views/rec_event_follows/new.html.erb
<h1>New rec_event_follow</h1>

<%= render 'form' %>

<%= link_to 'Back', rec_event_follows_path %>

app/views/rec_event_follows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recurring event:</strong>
  <%= @rec_event_follow.recurring_event_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @rec_event_follow.user_id %>
</p>

<%= link_to 'Edit', edit_rec_event_follow_path(@rec_event_follow) %> |
<%= link_to 'Back', rec_event_follows_path %>