config/routes.rb
GameOn::Application.routes.draw do

  match 'feedbacks' => 'feedbacks#create', :as => :feedback, via: :post
  match 'feedbacks/new' => 'feedbacks#new', :as => :new_feedback, via: :get
  
  resources :rec_event_follows do
    collection do
      get 'mygames'
    end
  end

  resources :event_invites

  resources :events do
    collection do
      get 'rsvp_yes'
      get 'rsvp_no'
      get 'rsvp_maybe'
      post 'comment'
    end
    resources :event_comments
  end

  resources :game_types
  resources :recurring_events do
    collection do
      get 'nearby'
      get 'follow'
      get 'unfollow'
    end
  end

  resources :locations do
    collection do
      get 'nearby'
    end
  end

  resources :user_profiles do
    collection do
      get 'editself'
    end
  end
  
  resources :home 
  
  authenticated :user do
    root :to => 'home#index', as: 'authorized'
  end
  root :to => "users#index"
  
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  

  

end

app/controllers/game_types_controller.rb
class GameTypesController < ApplicationController
  before_action :set_game_type, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  load_and_authorize_resource
  
  
  # GET /game_types
  # GET /game_types.json
  def index
    @game_types = GameType.all
    authorize! :index, GameType.new, :message => 'Not authorized as an administrator.'
  end

  # GET /game_types/1
  # GET /game_types/1.json
  def show
    authorize! :show, @game_type, :message => 'Not authorized as an administrator.'
  end

  # GET /game_types/new
  def new
    @game_type = GameType.new
    authorize! :create, @game_type, :message => 'Not authorized as an administrator.'
  end

  # GET /game_types/1/edit
  def edit
    authorize! :edit, @game_type, :message => 'Not authorized as an administrator.'
  end

  # POST /game_types
  # POST /game_types.json
  def create
    @game_type = GameType.new(game_type_params)
    authorize! :create, @game_type, :message => 'Not authorized as an administrator.'
    respond_to do |format|
      if @game_type.save
        format.html { redirect_to @game_type, notice: 'Game type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @game_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_types/1
  # PATCH/PUT /game_types/1.json
  def update
    authorize! :update, @game_type, :message => 'Not authorized as an administrator.'
    respond_to do |format|
      if @game_type.update(game_type_params)
        format.html { redirect_to @game_type, notice: 'Game type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_types/1
  # DELETE /game_types/1.json
  def destroy
    authorize! :destroy, @game_type, :message => 'Not authorized as an administrator.'
    @game_type.destroy
    respond_to do |format|
      format.html { redirect_to game_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_type
      @game_type = GameType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_type_params
      params[:game_type].permit(:name, :level1, :level2, :level3, :level4, :level5)
    end
end

app/helpers/game_types_helper.rb
module GameTypesHelper
end

app/views/game_types/_form.html.erb
<%= simple_form_for(@game_type) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :name, :input_html => {:class => 'form-control' } %>
    <%= f.input :level1, :input_html => {:class => 'form-control' } %>
    <%= f.input :level2, :input_html => {:class => 'form-control' } %>
    <%= f.input :level3, :input_html => {:class => 'form-control' } %>
    <%= f.input :level4, :input_html => {:class => 'form-control' } %>
    <%= f.input :level5, :input_html => {:class => 'form-control' } %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/game_types/edit.html.erb
<h1>Editing game_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @game_type %> |
<%= link_to 'Back', game_types_path %>

app/views/game_types/index.html.erb
<h1>Listing game_types</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @game_types.each do |game_type| %>
      <tr>
        <td><%= link_to 'Show', game_type %></td>
        <td><%= link_to 'Edit', edit_game_type_path(game_type) %></td>
        <td><%= link_to 'Destroy', game_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game type', new_game_type_path %>

app/views/game_types/new.html.erb
<h1>New game_type</h1>

<%= render 'form' %>

<%= link_to 'Back', game_types_path %>

app/views/game_types/show.html.erb
<h4><%= @game_type.name %></h4>


<span class="stars">1</span> <%= @game_type.level1 %>
<br><br>
<span class="stars">2</span> <%= @game_type.level2 %>
<br><br>
<span class="stars">3</span> <%= @game_type.level3 %>
<br><br>
<span class="stars">4</span> <%= @game_type.level4 %>
<br><br>
<span class="stars">5</span> <%= @game_type.level5 %>