config/routes.rb
GameOn::Application.routes.draw do

  match 'feedbacks' => 'feedbacks#create', :as => :feedback, via: :post
  match 'feedbacks/new' => 'feedbacks#new', :as => :new_feedback, via: :get
  
  resources :rec_event_follows do
    collection do
      get 'mygames'
    end
  end

  resources :event_invites

  resources :events do
    collection do
      get 'rsvp_yes'
      get 'rsvp_no'
      get 'rsvp_maybe'
      post 'comment'
    end
    resources :event_comments
  end

  resources :game_types
  resources :recurring_events do
    collection do
      get 'nearby'
      get 'follow'
      get 'unfollow'
    end
  end

  resources :locations do
    collection do
      get 'nearby'
    end
  end

  resources :user_profiles do
    collection do
      get 'editself'
    end
  end
  
  resources :home 
  
  authenticated :user do
    root :to => 'home#index', as: 'authorized'
  end
  root :to => "users#index"
  
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  

  

end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :name, :email, :website, :longitude, :latitude, :address, :phone_number
  has_many :recurring_events, dependent: :destroy
  has_many :events, dependent: :destroy
  
  geocoded_by :address do |obj, results|
    if geo = results.first
      obj.address = geo.formatted_address
      obj.latitude = geo.latitude
      obj.longitude = geo.longitude
    end
  end
  before_validation :geocode, :if => :address_changed?
  
  validates_presence_of :name, :address
  validates_uniqueness_of :address, :case_sensitive => false
  
  
  def self.search(search)
    if search
      near( "%#{search}%", 20)
    else
      near( '92127', 20)
    end
  end
  
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  load_and_authorize_resource
  
  # GET /locations
  # GET /locations.json
  def index
      @locations = Location.all 
      authorize! :index, Location.new, :message => 'Not authorized as an administrator.'
  end
  
  # GET /locations/1
  # GET /locations/1.json
  def show
    authorize! :show, @location, :message => 'Not authorized as an administrator.'
  end

  # GET /locations/new
  def new
    @location = Location.new
    authorize! :create, @location, :message => 'Not authorized as an administrator.'
  end

  # GET /locations/1/edit
  def edit
    authorize! :edit, @location, :message => 'Not authorized as an administrator.'
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)
    authorize! :create, @location, :message => 'Not authorized as an administrator.'
    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render action: 'show', status: :created, location: @location }
      else
        format.html { render action: 'new' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    authorize! :update, @location, :message => 'Not authorized as an administrator.'
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    authorize! :destroy, @location, :message => 'Not authorized as an administrator.'
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
  
  def nearby
    authorize! :nearby, Location.new, :message => 'Not authorized as an administrator.'
    @has_distance = true
    if !params[:search] || params[:search] == ""
      params[:search] = get_home_address().presence || request.location.address
    end   
    
    @locations  = Location.paginate(:page => params[:page]).near(params[:search], 20) 
    if @locations.count.zero?
      @locations = Location.paginate(:page => params[:page]).find(:all)
      @has_distance = false
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    def get_home_address
      profile = UserProfile.find_or_create_by_user_id( current_user.id)
      return profile.home_address
    end
  
    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params[:location]
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= simple_form_for(@location, html: {novalidate: true}) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :name, :input_html => {:class => 'input-xxlarge form-control'} %>
    <%= f.input :address, :input_html => {:class => 'input-xxlarge form-control'} %>
    <%= f.input :email, :input_html => {:class => 'input-xlarge form-control'} %>
    <%= f.input :website, :input_html => {:class => 'input-xlarge form-control'} %>
  </div>
  <br>
  <div class="actions">
    <%= f.button :submit, :class => 'btn btn-success'%>
  </div>
<% end %>

app/views/locations/_nearby.html.erb
<%= form_tag("/locations/nearby", {method: "get"}) do %>
<%= text_field_tag(:search, params[:search],  {class: 'col-lg-10 col-md-10 col-sm-9 col-xs-9', :autofocus => true}) %>
<%= submit_tag("Search", {class: 'btn btn-success btn-xs col-lg-2 col-md-2 col-sm-3 col-xs-3'}) %>
<% end %>
<br><br>

<% if !@locations.count.zero? %>
  
  <% @locations.each do | l | %>
    <div class="location">
      <%= link_to l do %>
        <div style='position:relative'>
          <span class='linkedspan'></span>       
          <span>
            <strong>
            <%= link_to l.name,  l %> 
            </strong>
          </span> 
          <% if @has_distance %>
            <span class='pull-right hidden-xs hidden-sm'><%= number_with_precision(l.distance, :precision => 1) %> miles away</span>  
          <% end %>
          <div>
            <%= l.address %>
          </div>
          <% if @has_distance %>
            <span class='visible-xs visible-sm'><%= number_with_precision(l.distance, :precision => 1) %> miles away</span> 
          <% end %>
        </div>
      <br>
      <% end %>
    </div>
  <% end %>
  <div class='flickr_pagination'>
    <%= will_paginate @locations %>
  </div>


<% else %>
<p> No locations found near the search address. </p>
<% end %>

app/views/locations/_recurring_events.html.erb
<% @location.recurring_events.all(:order => "day, start_time").each do | r | %>
  <%= link_to r do %>
  <div style='position:relative; background-color:#efe; padding: 5px; margin-bottom:5px'>
    <span class='linkedspan'></span>       
    <span>
      <strong>
        <%= link_to Date::DAYNAMES[ r.day ],  r.location.name  %> 
        <%= " - " + r.game_type.name %> 
      </strong>
    </span> 
    <br>
    <%= r.name %>
    <div > <%= get_timestring( r.start_time, r.end_time ) %> </div>
    <span class="stars"> <%= r.level %></span> 
  </div>
  
  <% end %>
<% end %>

app/views/locations/edit.html.erb
<h3>Edit location</h3>

<%= render 'form' %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.name %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/nearby.html.erb
<h3 style="margin-top: 0px">Search for locations</h3>
<div id='nearbyLocations' >
  <%= render 'nearby' %>  
</div>
<br>
<div>
  <%= link_to "Add new location", new_location_path, :class => 'btn btn-primary' %>
</div>

app/views/locations/new.html.erb
<h3>New location</h3>

<%= render 'form' %>

app/views/locations/show.html.erb
<h3><%= @location.name %></h3>

<p>
  <%= @location.address %>
</p>
<div class="collapse-group">
   <div class="collapse">
      <addressmap><%= @location.address %></addressmap>
    </div>
    <a id="mapbutton" class="btn btn-info" style="color:#fff" href="#">
     <span class="glyphicon glyphicon-map-marker"></span> View map &raquo;</a>
</div>
<br>

<% if !@location.recurring_events.count.zero? %>
  <h4>Weekly Games</h4>
  <%= render 'recurring_events' %>

<% end %>
<% if can? :update, @location %>
  <%= link_to 'Add Weekly Game', new_recurring_event_path(location_id: @location), :class => 'btn btn-success', :style => "color:#ffffff" %>
<% end %>
<br><br>
<% if can? :update, @location %>
<%= link_to 'Edit Location', edit_location_path(@location), :class => 'btn btn-primary', :style => "color:#ffffff" %> 
<% end %>